"""empty message

Revision ID: 15140aa3b6bc
Revises: a00e68bba66e
Create Date: 2016-09-12 13:49:58.482898

"""

# revision identifiers, used by Alembic.
revision = '15140aa3b6bc'
down_revision = 'a00e68bba66e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_experiment')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_experiment',
    sa.Column('activity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('experiment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], [u'activity.id'], name=u'activity_experiment_ibfk_1'),
    sa.ForeignKeyConstraint(['experiment_id'], [u'experiment.id'], name=u'activity_experiment_ibfk_2'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
