"""empty message

Revision ID: 16d60457aa72
Revises: 2f6b24e435d8
Create Date: 2016-09-15 12:19:27.888313

"""

# revision identifiers, used by Alembic.
revision = '16d60457aa72'
down_revision = '2f6b24e435d8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('tolerance', sa.Integer(), nullable=True))
    op.drop_constraint(u'assignment_ibfk_1', 'assignment', type_='foreignkey')
    op.drop_column('assignment', 'participant_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('participant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'assignment_ibfk_1', 'assignment', 'user', ['participant_id'], ['id'])
    op.drop_column('activity', 'tolerance')
    ### end Alembic commands ###
