"""empty message

Revision ID: 1eef7a613153
Revises: 2f6b24e435d8
Create Date: 2016-09-15 15:38:17.477408

"""

# revision identifiers, used by Alembic.
revision = '1eef7a613153'
down_revision = '2f6b24e435d8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'tolerance')
    op.drop_index('ix_experiment_name', table_name='experiment')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_experiment_name', 'experiment', ['name'], unique=False)
    op.add_column('activity', sa.Column('tolerance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
