"""empty message

Revision ID: 2f6b24e435d8
Revises: 15140aa3b6bc
Create Date: 2016-09-14 12:30:51.310483

"""

# revision identifiers, used by Alembic.
revision = '2f6b24e435d8'
down_revision = '15140aa3b6bc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('prompt', sa.String(length=500), nullable=True))
    op.add_column('activity', sa.Column('title', sa.String(length=500), nullable=True))
    op.drop_constraint(u'assignment_ibfk_1', 'assignment', type_='foreignkey')
    op.drop_column('assignment', 'participant_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('participant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'assignment_ibfk_1', 'assignment', 'user', ['participant_id'], ['id'])
    op.drop_column('activity', 'title')
    op.drop_column('activity', 'prompt')
    ### end Alembic commands ###
