"""empty message

Revision ID: 3f0c6631c001
Revises: None
Create Date: 2016-08-25 12:10:38.138994

"""

# revision identifiers, used by Alembic.
revision = '3f0c6631c001'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('answer', sa.Integer(), nullable=True))
    op.add_column('activity', sa.Column('lower_bound', sa.Integer(), nullable=True))
    op.add_column('activity', sa.Column('upper_bound', sa.Integer(), nullable=True))
    op.add_column('result', sa.Column('integer', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'integer')
    op.drop_column('activity', 'upper_bound')
    op.drop_column('activity', 'lower_bound')
    op.drop_column('activity', 'answer')
    ### end Alembic commands ###
