"""empty message

Revision ID: a00e68bba66e
Revises: 3c8b41553137
Create Date: 2016-09-09 17:24:13.999370

"""

# revision identifiers, used by Alembic.
revision = 'a00e68bba66e'
down_revision = '3c8b41553137'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result_choice',
    sa.Column('choice_id', sa.Integer(), nullable=True),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['choice_id'], [u'choice.id'], ),
    sa.ForeignKeyConstraint(['result_id'], [u'result.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result_choice')
    ### end Alembic commands ###
